cancelled notifications if validated
PS C:\Users\Marou\Documents\Dev\moto> flutter run
Launching lib\main.dart on SM S938B (wireless) in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > An issue was found when checking AAR metadata:

       1.  Dependency ':flutter_local_notifications' requires core library desugaring to be enabled
           for :app.

           See https://developer.android.com/studio/write/java8-support.html for more
           details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 11s
Running Gradle task 'assembleDebug'...                             12,1s
Error: Gradle task assembleDebug failed with exit code 1
PS C:\Users\Marou\Documents\Dev\moto>